FROM mcr.microsoft.com/devcontainers/universal:latest


# Set up working directory
WORKDIR /workspace

# Install required Python packages
RUN pip install --upgrade pip && \
    pip install mkdocs

# Set up default command
CMD ["bash"]